from __future__ import annotations

from pathlib import Path


def _transition_rows(records: list[dict[str, object]]) -> str:
    lines = ["| Before | After OOF | N |", "|---|---|---:|"]
    for record in records:
        lines.append(
            f"| `{record['BEFORE_CLASS']}` | `{record['OOF_CLASS']}` | "
            f"{int(record['N']):,} |"
        )
    return "\n".join(lines)


def _format_optional(value: object, digits: int = 3) -> str:
    if value is None:
        return "not available"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def render_bundle_build_summary(manifest: dict[str, object]) -> str:
    null_summary = manifest["full_pipeline_permutation_null_summary"]
    bootstrap_count = int(manifest["n_bootstrap_robust_95"])
    robust_count = int(manifest["n_robust_diagnostic_subset"])
    transitions = _transition_rows(manifest["strict_candidate_transition_table"])
    primary_transitions = _transition_rows(manifest["primary_cohort_transition_table"])
    injection_rows = manifest.get("injection_recovery_summary", [])
    injection_lines = [
        "| Noise model | Signal | K, km/s | Period, days | e | Detection fraction | N |",
        "|---|---|---:|---:|---:|---:|---:|",
    ]
    for row in injection_rows:
        injection_lines.append(
            "| `{NOISE_MODEL}` | `{SIGNAL_MODEL}` | {AMPLITUDE_KMS:g} | "
            "{PERIOD_DAYS} | {ECCENTRICITY:g} | {DETECTION_FRACTION:.4f} | "
            "{N_TRIALS:,} |".format(
                **{
                    **row,
                    "PERIOD_DAYS": (
                        "-" if row.get("PERIOD_DAYS") is None else f"{row['PERIOD_DAYS']:g}"
                    ),
                }
            )
        )
    injection_table = "\n".join(injection_lines)
    return f"""# DESI RV Variables Aggregate Build

This report is generated by `desi-rv-variables` from the sanitized build
manifest. It contains aggregate outcomes only, no ranked source IDs. This is an
independent exploratory analysis and not an official DESI Collaboration data
product or a variable-star catalogue.

## Frozen Candidate Cohort

- Input strict screening sources: {int(manifest['n_strict_screening_candidates_input']):,}
- Complete, single-component OOF sources: {int(manifest['n_strict_screening_candidates_primary_complete_case']):,}
- Before-rule outliers in that cohort: {int(manifest['n_strict_screening_candidates_before_outlier_primary']):,}
- OOF outliers in that cohort: {int(manifest['n_strict_screening_candidates_oof_outlier_primary']):,}
- `OUTLIER -> BELOW_SCREENING_THRESHOLD`: {int(manifest['n_strict_screening_candidates_reclassified_primary']):,}
- Classification-change fraction: {_format_optional(manifest['oof_reclassification_fraction'])}

The fraction above is a descriptive change under the diagnostic OOF correction.
It is not a causal estimate of calibration contamination.

{transitions}

## All Primary Sources

The same frozen rule is evaluated in both directions for every complete,
single-component source, not only for the previously selected candidates.

- Non-strict primary sources: {int(manifest['n_primary_non_strict_sources']):,}
- New OOF outliers outside the frozen strict list: {int(manifest['n_new_oof_outliers_not_in_strict_screening']):,}
- Corresponding fraction: {_format_optional(manifest['new_oof_outlier_fraction'])}

{primary_transitions}

## Full-Pipeline Null Control

- Exposure-level night permutations: {int(null_summary['n_permutations']):,}
- Median null transitions: {_format_optional(null_summary['median_outlier_to_below_screening_threshold'])}
- Null range: {_format_optional(null_summary['min_outlier_to_below_screening_threshold'])} to {_format_optional(null_summary['max_outlier_to_below_screening_threshold'])}
- Permutations at least as large as the real transition count: {_format_optional(null_summary['n_ge_real_outlier_to_below_screening_threshold'])}
- Corrected empirical exceedance probability: {_format_optional(null_summary['corrected_empirical_exceedance_probability'])}
- Median unscorable sources per permutation: {_format_optional(null_summary['median_unscorable'])}
- Minimum candidate-epoch exposure-map coverage: {_format_optional(null_summary['min_exposure_map_coverage_fraction'], digits=6)}

Each permutation assigns one shuffled night to each physical exposure within a
program, refits all source-disjoint fold models, and then repeats candidate-level
scoring. This is the primary candidate-level negative control.

The real transition count is not extreme under this control. It therefore does
not support an excess candidate-reclassification claim attributable to the real
night structure; the observed 12.75% remains descriptive only.

## Offset And Source Robustness

- Sources retaining the outlier classification in at least 95% of scorable
  source-bootstrap offset realizations: {bootstrap_count:,}
- Automated robust diagnostic subset: {robust_count:,}

The robust diagnostic subset additionally requires leave-one-epoch-out survival,
at least two disjoint significant epoch pairs, and evidence not confined to a
cross-program transition. It is a triage subset, not a high-confidence catalogue.

## Control Populations

- Cadence-matched inspection controls: {int(manifest['n_cadence_matched_inspection_control_sources']):,}
- Injection-recovery base sources: {int(manifest['n_injection_recovery_base_population_sources']):,}
- Sources in both populations: {int(manifest['n_control_sources_in_both_inspection_and_injection']):,}

These populations are separately defined and substantially overlapping. The
inspection controls are outcome-conditioned and are not an empirical null. The
injection base does not require a stable observed outcome because simulations
replace its measured velocities with synthetic values.

## Injection-Recovery Sensitivity

Synthetic velocities replace observed velocities on real cadence and error
templates. The table shows predeclared null and representative Keplerian cells;
the full grid is in `injection_recovery.csv`.

{injection_table}

These simulations compare Gaussian and heavy-tailed noise plus approximate
label-level bootstrap offset uncertainty. They do not determine astrophysical
prevalence and therefore do not by themselves calibrate catalogue FDR.

## Reproducibility

- `desi-rv-variables` commit: `{manifest['repositories']['desi_rv_variables_commit']}`
- `desi-rv-audit` artifact commit: `{manifest['repositories']['desi_rv_audit_artifact_commit']}`
- Fold hash: `{manifest['parameters']['fold_hash_algorithm']}`
- Full input/output hashes and package versions: `build_manifest_public.json`

The split is source-disjoint, not night-disjoint. The workflow was developed on
DESI DR1 MAIN and remains exploratory until the frozen confirmation protocol is
run on untouched data.
"""


def write_bundle_build_summary(manifest: dict[str, object], path: str | Path) -> None:
    Path(path).write_text(render_bundle_build_summary(manifest), encoding="utf-8")
